name: Publish Website over SFTP
on: 
    push:
      branches: 
        - master
    pull_request:
      branches:
        - master
jobs:
  SCP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2.1.0

    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.ALI_IP }}
        username: ${{ secrets.SFTP_USER }}
        password: ${{ secrets.ALI_PASSWORD }}
        port: 22
        rm: 1
        source: "./*"
        target: "/www/wwwroot/vein/"

    # - name: deploy file
    #     uses: wlixcc/SFTP-Deploy-Action@v1.0
    #     with:
    #       username: ${{ secrets.SFTP_USER }} 
    #       server: ${{ secrets.ALI_IP }} 
    #       private_key: ${{ secrets.SSH_KEY }} 
    #       local_path: './*'
    #       remote_path: '/www/wwwroot/vein.ink/' #make sure dir exist
    #       args: '-o ConnectTimeout=15'

    # - name: FTP-Deploy-Action
    #   uses: SamKirkland/FTP-Deploy-Action@3.1.1
    #   with:
    #     ftp-server: ${{ secrets.SFTP_SERVER }}
    #     ftp-username: ${{ secrets.SFTP_USER }}
    #     ftp-password: ${{ secrets.ALI_PASSWORD }}
    #     git-ftp-args: --insecure # if your certificate is setup correctly this can be removed (see known-hosts argument)
