name: Publish Website over SFTP
on: 
    push:
      branches: 
        - master
    pull_request:
      branches:
        - master
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.SFTP_SERVER }}
        ftp-username: ${{ secrets.SFTP_USER }}
        ftp-password: ${{ secrets.ALI_PASSWORD }}
        git-ftp-args: --insecure # if your certificate is setup correctly this can be removed (see known-hosts argument)
